class Monitor:
    @property
    def name(self) -> str: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def position(self) -> tuple[int, int]: ...
    @property
    def scale_factor(self) -> float: ...
    @property
    def refresh_rate_millihertz(self) -> int | None: ...
    @property
    def handle(self) -> int: ...

    def set_primary(self) -> None: ...


def get_primary_monitor() -> Monitor: ...
def get_window_monitor(hwnd: int) -> Monitor: ...
def enumerate_monitors() -> list[Monitor]: ...
def get_monitor_from_point(x: int, y: int) -> Monitor: ...

def set_primary_monitor(display_name: str) -> None: ...